routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/chart', function () {
    return view('admin/chart');
});

Route::get('/reset', function () {
    return view('auth/passwords/reset');
});

Route::resource('pages','AttendenceController');

Route::resource('admin','UsersController');

Route::resource('user','AdminAttendenceController');

Route::resource('leaves','Leaveholidays');

Auth::routes();

Route::get('/home', 'HomeController@index');



//
Route::get('/leave', 'Leaveholiday@leave');
Route::get('/holiday', 'Leaveholiday@holiday');

resources/views/admin/Leave.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif

        <br><br>
    <div class="row">
        <div class="col-md-12 col-md-offset-4">
            {{--{!! Form::open(['route' => 'leave']) !!}--}}
        {!!   Form::open(array('route' => array('leaves.store'), 'method' => 'post')) !!}
        <div class="col-md-3">
            <b>Date:</b> <input type="date" name="date" class="form-control input-lg">
            <br><br>
            <div class="row">
                <div class="col-sm-6">
                    {!! Html::linkRoute('user.index', 'Cancel', array(), array('class' => 'btn btn-danger btn-block')) !!}
                </div>
                <div class="col-sm-6">
                    {{ Form::submit('Save Changes',['class'=>'btn btn-success btn-block']) }}
                </div>
            </div>
        </div>

        {!!   Form::close() !!}
        </div>
    </div>

@endsection

resources/views/admin/adminview.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())
        <script>window.location.href = '{{route("login")}}';</script>
    @endif

    @include('partials.adminviewTable_partial')
<div class="container-fluid">

    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="col-md-6">

                {!! $chart->render() !!}

            </div>
            <div class="col-md-6">

                @include('partials.monthchart')

            </div>

        </div>
    </div>
</div>

<br><br>

  {{--  <div id="100">
        @include('partials.monthchart')
    </div>--}}






{{--<script>
    $('button').click(function addseries(e){
            $.ajax({
                type:'get',
                url:'user.create',
                data: {id:id

                },error: function(jqXHR, textStatus, errorThrown) { // What to do if we fail
                    console.log(JSON.stringify(jqXHR));
                    console.log("AJAX error: " + textStatus + ' : ' + errorThrown);
                }
            });
        }
        function getMessage(){
            $.ajax({
                type:'get',
                url:"{{url('user.create')}}",
                data: {

                }
            });
        }
</script>--}}




    @endsection

resources/views/admin/chart.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif

    <div class="row">
        <div class="col-md-8 col-md-offset-2">

          {!! $chart->render() !!}

            <div class="row">
                <div class="col-md-10 col-md-offset-1">

                    <div class="col-md-10 col-md-offset-0">
                        <button   id="1" > <b>&lArr;</b> </button>
                    </div>

                    <div class="col-md-2 col-md-offset-0">
                        <a   id="2" > <b>&rArr;</b> </a>
                    </div>

                </div>
            </div>

        </div>
    </div>

@endsection

resources/views/admin/edit.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif


    <div class="row">
        <div class="col-md-12 col-md-offset-4">
        {!! Form::model($record, ['route' => ['user.update', $record->id], 'method'=>'PUT']) !!}
        <div class="col-md-3">
            {{ Form::label('punch_in', 'Punch In:') }}
            {{ Form::time('punch_in', null, ["class" => 'form-control input-lg']) }}
            <br>
            {{ Form::label('punch_out', "Punch Out:", ['class' => 'form-spacing-top']) }}
            {{ Form::time('punch_out', null, ['class' => 'form-control input-lg']) }}
            <br>
            <div class="row">
                <div class="col-sm-6">
                    {!! Html::linkRoute('user.index', 'Cancel', array($record->id), array('class' => 'btn btn-danger btn-block')) !!}
                </div>
                <div class="col-sm-6">
                    {{ Form::submit('Save Changes',['class'=>'btn btn-success btn-block']) }}
                </div>
            </div>
        </div>

        {!! Form::close() !!}
        </div>
    </div>

@endsection

resources/views/admin/edit1.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif

        <br><br>
    <div class="row">
        <div class="col-md-12 col-md-offset-4">
        {!!   Form::open(array('route' => array('user.store'), 'method' => 'POST')) !!}
        <div class="col-md-3">
            <b>Date:</b> <input type="date" name="date" class="form-control input-lg">
            <br>
            <b>Punch In:</b> <input type="time" name="punch_in" class="form-control input-lg">
            <br>
            <b>Punch Out:</b> <input type="time" name="punch_out" class="form-control input-lg">
            <br><br>
            <div class="row">
                <div class="col-sm-6">
                    {!! Html::linkRoute('user.index', 'Cancel', array(), array('class' => 'btn btn-danger btn-block')) !!}
                </div>
                <div class="col-sm-6">
                    {{ Form::submit('Save Changes',['class'=>'btn btn-success btn-block']) }}
                </div>
            </div>
        </div>

        {!!   Form::close() !!}
        </div>
    </div>

@endsection

resources/views/admin/holiday.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif

        <br><br>
    <div class="row">
        <div class="col-md-12 col-md-offset-4">
            {!!   Form::open(array('route' => ['leaves.update', 1], 'method' => 'PUT')) !!}
        <div class="col-md-3">
            <b>Date:</b> <input type="date" name="date" class="form-control input-lg">

            <br><br>
            <div class="row">
                <div class="col-sm-6">
                    {!! Html::linkRoute('user.index', 'Cancel', array(), array('class' => 'btn btn-danger btn-block')) !!}
                </div>
                <div class="col-sm-6">
                    {{ Form::submit('Save Changes',['class'=>'btn btn-success btn-block']) }}
                </div>
            </div>
        </div>

        {!!   Form::close() !!}
        </div>
    </div>

@endsection

resources/views/admin/show.blade.php
@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif
<?php
session_start();
?>
    <div class="container">
        <div class="row">
            <div class="col-md-2 ">
    {!! Html::linkRoute('user.index', '< BACK', array(), array('class' => 'btn btn-success ')) !!}

            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-3">
                <div class="panel panel-default">
                    <div class="panel-heading">Time</div>
                      <div class="panel-body">
                          <b>Punch In:</b> &ensp;&ensp;&ensp;{{ $record->punch_in }}<br>
                          <b>Punch Out:</b>&ensp;&ensp;{{ $record->punch_out }}<br>
                          <b>Duration:</b> &ensp;&ensp;&ensp;{{ $record->duration }}<br><br><br>

                        <div class="container">


                            {!! Form::open(['route' => ['user.destroy', $record->id],'method' => 'DELETE']) !!}
                            <div class="row">
                                <div class="col-sm-2">
                                    {!! Html::linkRoute('user.edit', 'Edit', array($record->id), array('class' => 'btn btn-success btn-block')) !!}
                                </div>
                                <div class="col-sm-2">


                                    {!! Form::submit('Delete', ['class' => 'btn btn-danger btn-block']) !!}

                                    {!! Form::close() !!}
                                </div>
                            </div>

                        </div>
                          <script>
                              function myFunction() {
                                  window.location.href = '{{route("user.edit", $record->id)}}';
                              }
                              function myFunction1() {
                                  window.location.href = '{{route("user.destroy", $record->id)}}';



                              }
                          </script>
                      </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
@endsection

resources/views/admin/users.blade.php
<?php


if(!isset($_SESSION['dd'])){

        $_SESSION["dd"] = 1;

}

?>


@extends('layouts.app1')

@section('content')
    @if (Auth::guest())

        <script>window.location.href = '{{route("login")}}';</script>

    @endif

<script>

    function mouseoverPass() {
        var obj = document.getElementById('myPassword');
        obj.type = "text";
    }
    function mouseoutPass() {
        var obj = document.getElementById('myPassword');
        obj.type = "password";
    }


</script>


    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <table class="table table-bordered" >
                    <tr>
                        <th align='center' colspan="50px">

                            <div class="row">
                                <div class=" col-md-offset-4">

                                    <h2>Admin View</h2>

                                </div>
                            </div>

                        </th>
                    </tr>
                    {{--<tr>
                        <th align='center' colspan="50px">

                            <div class="row">
                                <div class=" col-md-offset-5">

                            <h3>EMPLOYEES</h3>

                                </div>
                            </div>

                        </th>
                    </tr>--}}
                    <tr align='center'>
                        <th> Sr </th>
                        <th> Name </th>
                        <th> Email </th>
                        <th> Role </th>
                        {{--<th> Password </th>--}}
                        <th> Operations </th>


                    </tr>
                    <tr align='center'>
                    @foreach ($users as $user)

                        <?php $myid = $user->id; ?>
                        <tr>
                            <th>{{ $user->id }}</th>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>
                                <?php
                                    if($user->admin == null || $user->admin == 0){

                                        echo 'Employee';
                                    }elseif($user->admin == 1){

                                        echo 'Admin';
                                    }
                                ?>
                            </td>
                            {{--<td>{{ $user->password }}</td>--}}
                            <td>
                                <button style="font-size:15px" onclick="window.location.href = '{{route("admin.show",$user->id )}}';"><i class="fa fa-search"></i></button>

                                <button style="font-size:15px" onclick="window.location.href = '{{route("pages.edit",$user->id )}}';"><i class="fa fa-trash" ></i></button>

                                <button style="font-size:15px" onclick="window.location.href = '{{route("admin.edit",$user->id )}}';"><i class="fa fa-pencil-square"></i></button>
                            </td>
                        </tr>

                     @endforeach

                    </tr>

                </table>
            </div>
        </div>
    </div>

<?php
if($_SESSION["dd"] == 2){
$_SESSION["dd"] = 1;
echo $_SESSION["dd"];
?>
    <script>
    $(document).ready(function(){
        $("#myModal").modal("show");
    } );
    </script>

    <?php
    }
    ?>

  <?php
  if($_SESSION["dd"] == 3){
  $_SESSION["dd"] = 1;
  echo $_SESSION["dd"];
  ?>
    <script>
        $(document).ready(function(){
            $("#myModal1").modal("show");
        } );
    </script>

    <?php
    }
    ?>




    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Edit</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        {!! Form::model($users11, ['route' => ['admin.update', $users11->id], 'method'=>'PUT']) !!}
                        <div class="col-md-8 col-md-offset-2">
                            {{ Form::label('name', 'Name:') }}
                            {{ Form::text('name', null, ["class" => 'form-control input-lg']) }}
                            <br>
                            {{ Form::label('email', "Email:", ['class' => 'form-spacing-top']) }}
                            {{ Form::text('email', null, ['class' => 'form-control input-lg']) }}
                            <br>

                            {{ Form::label('password', "Password:", ['class' => 'form-spacing-top']) }}

                            <div class="row">
                                <div class="col-sm-10">
                            {{--{{ Form::password('password1',  ['class' => 'form-control input-lg']) }}--}}
                                    <input type="password" name="password1" id="myPassword" class="form-control input-lg" />
                                </div>
                                <div class="col-sm-1">
                                    <button style="font-size:15px" onmouseover="mouseoverPass();" onmouseout="mouseoutPass();"><i class="fa fa-eye"></i></button>
                                </div>
                            </div>
                            <br>
                            <div class="row">
                                <div class="col-sm-6">
                                    {!! Html::linkRoute('admin.index', 'Cancel', array($users11->id), array('class' => 'btn btn-danger btn-block')) !!}
                                </div>
                                <div class="col-sm-6">
                                    {{ Form::submit('Save Changes',['class'=>'btn btn-success btn-block']) }}
                                </div>
                            </div>
                        </div>

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>

        </div>
    </div>

    <!-- Modal1 -->

    <div id="myModal1" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Confirm</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">

                            <br>
                            <div class="row">
                                <div class="col-sm-6">
                                    {!! Html::linkRoute('admin.index', 'Cancel', array($users11->id), array('class' => 'btn btn-danger btn-block')) !!}
                                </div>
                                <div class="col-sm-6">
                                    {{ Form::open(array('route' => array('admin.destroy', $user->id), 'method' => 'delete')) }}
                                    <button type="submit" class="btn btn-success btn-block">Delete</button>

                                    {{ Form::close() }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection